In [1]:
import numpy as np

In [5]:
arr=np.array([[[2,3,4],[5,6,7],[8,9,10]]])

In [6]:
arr

array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [11]:
arr2=np.array([1, 2, 3, 4])

In [13]:
arr2.dtype

dtype('int32')

In [15]:
arr2=np.array([1, 2, 3, 4],float)

In [16]:
arr2.dtype

dtype('float64')

In [4]:
import numpy as np

In [5]:
arr3=np. array([10, 20, 30])

In [6]:
arr3

array([10, 20, 30])

In [8]:
arr3=np.append(arr3,(40,50,60,70,80,90))

In [9]:
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
arr1=np.array([[1,2,3]])
arr2=np.array([[1,2,3]])

In [38]:
s=np.sum([[arr1],[arr2]],axis=0)

In [40]:
s

array([[[2, 4, 6]]])

In [42]:
array1=np.array([[[10,20,30],[40,50,60],[70,80,90]]])

In [43]:
array1

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [54]:
x = array1[0,0]

In [55]:
x

array([10, 20, 30])

In [ ]:
y=array1[0,1]