In [4]:
import numpy as np

In [15]:
num1=np.full((3,3),5)

In [16]:
num1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [1]:
import numpy as np

def sum_arrays(arrays):
    shape = arrays[0].shape
    for arr in arrays[1:]:
        if arr.shape != shape:
            raise ValueError("All arrays must have the same dimensions")
    
    result = np.zeros(shape)
    for arr in arrays:
        result += arr
    
    return result

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[2, 3, 4], [5, 6, 7]])
array3 = np.array([[3, 4, 5], [6, 7, 8]])

result = sum_arrays([array1, array2, array3])
print("Sum of arrays:")
print(result)


Sum of arrays:
[[ 6.  9. 12.]
 [15. 18. 21.]]


In [3]:

def top_left_sub_matrix(matrix, N, M):
   
    if len(matrix) < N or len(matrix[0]) < M:
        raise ValueError("Matrix dimensions are smaller than specified sub-matrix size")

    sub_matrix = [row[:M] for row in matrix[:N]]
    
    return sub_matrix

matrix = [
    [1, 2, 3, 4],
    [4, 5, 6, 7],
    [7, 8, 9, 10]
]

N = 2
M = 2

result = top_left_sub_matrix(matrix, N, M)
print(f"{N}x{M} Sub-matrix:")
for row in result:
    print(row)



2x2 Sub-matrix:
[1, 2]
[4, 5]


In [4]:
def sub_matrix(matrix, N, M):

    if len(matrix) < N or len(matrix[0]) < M:
        raise ValueError("Matrix dimensions are smaller than specified sub-matrix size")
    
    start_row = len(matrix) - N
    start_col = len(matrix[0]) - M
    
   
    sub_matrix = [row[start_col:start_col+M] for row in matrix[start_row:start_row+N]]
    
    return sub_matrix

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

N = 2
M = 2

result = sub_matrix(matrix, N, M)
print(f"{N}x{M} Sub-matrix:")
for row in result:
    print(row)


2x2 Sub-matrix:
[5, 6]
[8, 9]


In [5]:
import numpy as np

def solution(arr):
    mean_value = np.mean(arr)
    std_deviation = np.std(arr)
    
    result_dict = {
        'mean': mean_value,
        'std_dev': std_deviation
    }
    
    return result_dict

arr = np.array([1, 1, 1])
result = solution(arr)
print(result)


{'mean': 1.0, 'std_dev': 0.0}
